spring.application.name=OOP_Server_App
#spring.mongodb.uri=mongodb+srv://it25103239_db_user:ss4sgqzfc5Wtk3DK@oopproj.vz87d1u.mongodb.net/OOP_Database?retryWrites=true&w=majority&appName=OOP_Database
#spring.datasource.hikari.maxAllowedPacket=67108864
springdoc.packages-to-scan=sliit.oop_server_app.controller
springdoc.api-docs.enabled=true




# Database URL (replace 'mydatabase' with your schema name)
spring.datasource.url=jdbc:mysql://localhost:3306/oop_db?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=1234

# JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


