spring.application.name=OOP_Server_App
spring.mongodb.uri=mongodb+srv://it25103239_db_user:ss4sgqzfc5Wtk3DK@oopproj.vz87d1u.mongodb.net/OOP_Database?retryWrites=true&w=majority&appName=OOP_Database
spring.datasource.hikari.maxAllowedPacket=67108864


